("TSZ.DGO"
  (
  "static-screen.o"
  "plat-ag.go"
  "plat-eco-ag.go"
  "water-anim-village1-ag.go"
  "sharkey.o"
  "sharkey-ag.go"
  "village2-part.o"
  "test-zone-obs.o"
  "test-zone.go"
  )
)
