;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("AFO.DGO"
 ("static-screen.o"
  "plat-ag.go"
  "blocking-plane.o"
  "target-racer-h.o"
  "racer-part.o"
  "racer.o"
  "target-racer.o"
  "racer-states.o"
  "collide-reaction-racer.o"
  "eichar-racer+0-ag.go"
  "racer-ag.go"
  "plat-eco-ag.go"
  "ef-plane-ag.go"
  "babak-ag.go"
  ;;"beach-part.o"
  "afon-part.o"
  "water-anim-training-ag.go"
  "water-anim-sunken-ag.go"
  "sunken-water.o"
  "misty-part.o"
  "eichar-pole+0-ag.go"
  "pontoonten-ag.go"
  "village2-obs.o"
  "bounceytarp-ag.go"
  "bouncer.o"
  "lurkerworm.o"
  "lurkerworm-ag.go"
  "driller-lurker.o"
  "driller-lurker-ag.go"
  "cavecrystal-light.o" ;; for some reason this is needed for driller lurkers to work. also driller workers dont seem to have a nav mesh
  "twister.o"
  "villagep-obs.o"
  "warp-gate-switch-ag.go"
  "warpgate-ag.go"
  "training-part.o"
  ;; "basebutton.o"
  "snow-ram-h.o"
  "snow-ram-boss.o"
  "snow-ram.o"
  "snow-obs.o"
  "snow-part.o"
  "target-snowball.o"
  "snowcam-ag.go"
  "ram-ag.go"
  "ram-boss-ag.go"
  "afoniddwr.go"
 ))
